app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('token', function () { return csrf_token(); });
Route::get('password-change', 'PasswordController@index')->name('password.edit');
Route::post('password-update', 'PasswordController@update')->name('password.update');


Route::group(['prefix' => 'admin', 'middleware' => 'auth.checkrole','as' => 'admin.'], function (){
    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function (){
        Route::get('', 'CategoriesController@index')->name('index');
        Route::get('create', 'CategoriesController@create')->name('create');
        Route::get('edit/{id}', 'CategoriesController@edit')->name('edit');
        Route::post('store', 'CategoriesController@store')->name('store');
        Route::post('update/{id}', 'CategoriesController@update')->name('update');
    });
    Route::group(['prefix' => 'products', 'as' => 'products.'], function (){
        Route::get('', 'ProductsController@index')->name('index');
        Route::get('create', 'ProductsController@create')->name('create');
        Route::get('edit/{id}', 'ProductsController@edit')->name('edit');
        Route::post('store', 'ProductsController@store')->name('store');
        Route::post('update/{id}', 'ProductsController@update')->name('update');
        Route::get('delete/{id}', 'ProductsController@destroy')->name('delete');
    });
    Route::group(['prefix' => 'clients', 'as' => 'clients.'], function (){
        Route::get('', 'ClientsController@index')->name('index');
        Route::get('create', 'ClientsController@create')->name('create');
        Route::get('edit/{id}', 'ClientsController@edit')->name('edit');
        Route::post('store', 'ClientsController@store')->name('store');
        Route::post('update/{id}', 'ClientsController@update')->name('update');
    });
    Route::group(['prefix' => 'orders', 'as' => 'orders.'], function (){
        Route::get('', 'OrdersController@index')->name('index');
        Route::get('/edit/{id}', 'OrdersController@edit')->name('edit');
        Route::post('/update/{id}', 'OrdersController@update')->name('update');
    });
    Route::group(['prefix' => 'coupons', 'as' => 'coupons.'], function (){
        Route::get('', 'CouponsController@index')->name('index');
        Route::get('create', 'CouponsController@create')->name('create');
        Route::get('edit/{id}', 'CouponsController@edit')->name('edit');
        Route::post('store', 'CouponsController@store')->name('store');
        Route::post('update/{id}', 'CouponsController@update')->name('update');
    });
});

Route::group(['prefix' => 'customer', 'as' => 'customer.'], function (){
    Route::group(['prefix' => 'order', 'as' => 'order.'], function (){


        Route::get('', 'CheckoutController@index')->name('index');
        Route::get('create', 'CheckoutController@create')->name('create');
        Route::get('edit/{id}', 'CheckoutController@edit')->name('edit');
        Route::post('store', 'CheckoutController@store')->name('store');
        Route::post('update/{id}', 'CheckoutController@update')->name('update');
    });
});

app/Models/Product.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Product extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'category_id',
        'name',
        'description',
        'price'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

}

app/Http/Controllers/ProductsController.php
<?php

namespace CodeDelivery\Http\Controllers;

use CodeDelivery\Http\Requests\AdminProductRequest;
use CodeDelivery\Repositories\CategoryRepository;
use CodeDelivery\Repositories\ProductRepository;

class ProductsController extends Controller
{
    private $repository;
    private $categoryRepository;

    public function __construct(ProductRepository $repository, CategoryRepository $categoryRepository)
    {
        $this->repository = $repository;
        $this->categoryRepository = $categoryRepository;
    }

    public function index()
    {
        $products = $this->repository->paginate();
        return view('admin.products.index', compact('products'));
    }

    public function create()
    {
        $categories = $this->categoryRepository->lists('name', 'id');
        return view('admin.products.create', compact('categories'));
    }

    public function store(AdminProductRequest $request)
    {
        $data = $request->all();
        $this->repository->create($data);
        return redirect()->route('admin.products.index');
    }

    public function edit($id)
    {
        $product = $this->repository->find($id);
        $categories = $this->categoryRepository->lists('name', 'id');
        return view('admin.products.edit', compact('product', 'categories'));
    }

    public function update(AdminProductRequest $request, $id)
    {
        $data = $request->all();
        $this->repository->update($data, $id);
        return redirect()->route('admin.products.index');
    }

    public function destroy($id)
    {
        $this->repository->delete($id);
        return redirect()->route('admin.products.index');
    }

}

resources/views/admin/products/_form.blade.php
<div class="form-group">
    {!! Form::label('category_id', 'Categoria:') !!}
    {!! Form::select('category_id', $categories, null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('name', 'Nome:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('description', 'Descrição:') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('price', 'Preço:') !!}
    {!! Form::text('price', null, ['class' => 'form-control']) !!}
</div>

resources/views/admin/products/create.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Novo produto</h3>

        @include('errors._check')

        {!! Form::open(['route' => 'admin.products.store', 'method' => 'post']) !!}

        @include('admin.products._form')

        <div class="form-group">
            {!! Form::submit('Criar produto', ['class' => 'btn btn-primary']) !!}
        </div>

        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/products/edit.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Editando produto</h3>

        @include('errors._check')

        {!! Form::model($product, ['route' => ['admin.products.update', $product->id], 'method' => 'post']) !!}

        @include('admin.products._form')

        <div class="form-group">
            {!! Form::submit('Salvar produto', ['class' => 'btn btn-primary']) !!}
        </div>

        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/products/index.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Produtos</h3>

        <a href="{{ route('admin.products.create') }}" class="btn btn-default">Novo Produto</a>
        <br><br>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>Produto</th>
                <th>Categoria</th>
                <th>Preço</th>
                <th>Ação</th>
            </tr>
            </thead>
            <tbody>
            @foreach($products as $product)
                <tr>
                    <td>{{ $product->id }}</td>
                    <td>{{ $product->name }}</td>
                    <td>{{ $product->category->name }}</td>
                    <td>{{ $product->price }}</td>
                    <td>
                        <a href="{{ route('admin.products.edit', $product->id) }}" class="btn btn-default btn-sm">Editar</a>
                        <a href="{{ route('admin.products.delete', $product->id) }}" class="btn btn-danger btn-sm">Deletar</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {!! $products->render() !!}

    </div>
@endsection