app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('token', function () { return csrf_token(); });
Route::get('password-change', 'PasswordController@index')->name('password.edit');
Route::post('password-update', 'PasswordController@update')->name('password.update');


Route::group(['prefix' => 'admin', 'middleware' => 'auth.checkrole','as' => 'admin.'], function (){
    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function (){
        Route::get('', 'CategoriesController@index')->name('index');
        Route::get('create', 'CategoriesController@create')->name('create');
        Route::get('edit/{id}', 'CategoriesController@edit')->name('edit');
        Route::post('store', 'CategoriesController@store')->name('store');
        Route::post('update/{id}', 'CategoriesController@update')->name('update');
    });
    Route::group(['prefix' => 'products', 'as' => 'products.'], function (){
        Route::get('', 'ProductsController@index')->name('index');
        Route::get('create', 'ProductsController@create')->name('create');
        Route::get('edit/{id}', 'ProductsController@edit')->name('edit');
        Route::post('store', 'ProductsController@store')->name('store');
        Route::post('update/{id}', 'ProductsController@update')->name('update');
        Route::get('delete/{id}', 'ProductsController@destroy')->name('delete');
    });
    Route::group(['prefix' => 'clients', 'as' => 'clients.'], function (){
        Route::get('', 'ClientsController@index')->name('index');
        Route::get('create', 'ClientsController@create')->name('create');
        Route::get('edit/{id}', 'ClientsController@edit')->name('edit');
        Route::post('store', 'ClientsController@store')->name('store');
        Route::post('update/{id}', 'ClientsController@update')->name('update');
    });
    Route::group(['prefix' => 'orders', 'as' => 'orders.'], function (){
        Route::get('', 'OrdersController@index')->name('index');
        Route::get('/edit/{id}', 'OrdersController@edit')->name('edit');
        Route::post('/update/{id}', 'OrdersController@update')->name('update');
    });
    Route::group(['prefix' => 'coupons', 'as' => 'coupons.'], function (){
        Route::get('', 'CouponsController@index')->name('index');
        Route::get('create', 'CouponsController@create')->name('create');
        Route::get('edit/{id}', 'CouponsController@edit')->name('edit');
        Route::post('store', 'CouponsController@store')->name('store');
        Route::post('update/{id}', 'CouponsController@update')->name('update');
    });
});

Route::group(['prefix' => 'customer', 'as' => 'customer.'], function (){
    Route::group(['prefix' => 'order', 'as' => 'order.'], function (){


        Route::get('', 'CheckoutController@index')->name('index');
        Route::get('create', 'CheckoutController@create')->name('create');
        Route::get('edit/{id}', 'CheckoutController@edit')->name('edit');
        Route::post('store', 'CheckoutController@store')->name('store');
        Route::post('update/{id}', 'CheckoutController@update')->name('update');
    });
});

app/Models/Order.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Order extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'client_id',
        'user_deliveryman_id',
        'total',
        'status'
    ];

    public function items()
    {
        return $this->hasMany(OrderItem::class);
    }

    public function deliveryman()
    {
        return $this->belongsTo(User::class, 'user_deliveryman_id', 'id');
    }

    public function client()
    {
        return $this->belongsTo(Client::class);
    }
}

app/Http/Controllers/OrdersController.php
<?php

namespace CodeDelivery\Http\Controllers;

use CodeDelivery\Http\Requests\AdminOrderRequest;
use CodeDelivery\Repositories\OrderRepository;
use CodeDelivery\Repositories\UserRepository;
use CodeDelivery\Services\OrderService;

class OrdersController extends Controller
{
    private $repository;
    private $userRepository;
    private $orderService;

    public function __construct(OrderRepository $repository, UserRepository $userRepository, OrderService $orderService)
    {
        $this->repository = $repository;
        $this->userRepository = $userRepository;
        $this->orderService = $orderService;
    }

    public function index()
    {
        $orders = $this->repository->paginate();
        $status = $this->orderService->getStatusList();
        return view('admin.orders.index', compact('orders', 'status'));
    }

    public function edit($id)
    {
        $order = $this->repository->find($id);
        $status = $this->orderService->getStatusList();
        $deliveryman = $this->userRepository->getDeliveryman();
        return view('admin.orders.edit', compact('order', 'status', 'deliveryman'));
    }

    public function update(AdminOrderRequest $request, $id)
    {
        $data = $request->all();
        $this->repository->update($data, $id);
        return redirect()->route('admin.orders.index');
    }

}

resources/views/customer/order/create.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Novo Pedido</h3>

        @include('errors._check')

        <div class="container">
            {!! Form::open(['route' => 'customer.order.store', 'method' => 'post']) !!}

            <div class="form-group">
                {!! Form::label('total', 'Total:') !!}
                <p id="total"></p>
                <a href="#" class="btn btn-default" id="btnNewItem">Novo item</a>
                <br><br>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>Produto</th>
                        <th>Quantidade</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>
                            <select name="items[0][product_id]" id="" class="form-control">
                                @foreach($products as $product)
                                    <option value="{{ $product->id }}" data-price="{{ $product->price }}">{{ $product->name }} --- {{ $product->price }}</option>
                                @endforeach
                            </select>
                        </td>
                        <td>
                            {!! Form::text('items[0][qty]', 1, ['class' => 'form-control']) !!}
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>

            <div class="form-group">
                {!! Form::submit('Criar checkout', ['class' => 'btn btn-primary']) !!}
            </div>

            {!! Form::close() !!}
        </div>


    </div>
@endsection

@section('post-script')
    <script>
        $('#btnNewItem').click(function () {
            var row = $('table tbody > tr:last'),
                newRow = row.clone(),
                length = $('table tbody tr').length;

            newRow.find('td').each(function () {
                var td = $(this);
                input = td.find('input,select');
                name = input.attr('name');
                input.attr('name', name.replace((length-1) + '', length + ''));
            });

            newRow.find('input').val(1);
            newRow.insertAfter(row);
            calculateTotal();
        });
        
        function calculateTotal() {
            var total = 0,
                trLen = $('table tbody tr').length,
                tr = null, price, qty;

            for (var i = 0; i < trLen; i++){
                tr = $('table tbody tr').eq(i);
                price = tr.find(':selected').data('price');
                qty = tr.find('input').val();
                total += price * qty;
            }

            $('#total').html(total);
        }

        $(document.body).on('click', 'select', function () {
            calculateTotal();
        });

        $(document.body).on('blur', 'input', function () {
            calculateTotal();
        });

        $('input[name*=qty]').blur(function () {
            calculateTotal();
        })
    </script>
@endsection

resources/views/customer/order/edit.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Editando categoria</h3>

        @include('errors._check')

        {!! Form::model($category, ['route' => ['admin.categories.update', $category->id], 'method' => 'post']) !!}

        @include('admin.categories._form')

        <div class="form-group">
            {!! Form::submit('Salvar categoria', ['class' => 'btn btn-primary']) !!}
        </div>

        {!! Form::close() !!}
    </div>
@endsection

resources/views/customer/order/index.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Categorias</h3>

        <a href="{{ route('admin.categories.create') }}" class="btn btn-default">Nova Categoria</a>
        <br><br>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Ação</th>
            </tr>
            </thead>
            <tbody>
            @foreach($categories as $category)
                <tr>
                    <td>{{ $category->id }}</td>
                    <td>{{ $category->name }}</td>
                    <td>
                        <a href="{{ route('admin.categories.edit', $category->id) }}" class="btn btn-default btn-sm">Editar</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

        {!! $categories->render() !!}

    </div>
@endsection